[package]
name = "apidoc_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
glob = "0.3.1"
linked-hash-map = "0.5.6"
yaml-rust = "0.4.5"
